FROM node:20-alpine as builder
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
COPY vite.config.js ./
RUN npm install
COPY . .
# 确保所有脚本和文件有读取和执行权限
# 特别是对于 'npm run build' 可能调用的脚本或文件
RUN chmod +x ./node_modules/.bin/*
# 确保项目文件也有执行权限
RUN chmod -R +x .
RUN npm run build 
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]